name = "test-shop"
client_id = "REPLACE_WITH_SHOPIFY_API_KEY"
application_url = "https://example.com"
embedded = true
handle = "test-shop"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "REPLACE_WITH_DEV_STORE.myshopify.com"

[access_scopes]
scopes = "read_orders,write_orders,write_metafields"

[auth]
redirect_urls = [
  "https://example.com/auth/callback",
  "https://example.com/auth/shopify/callback",
  "https://example.com/api/auth/callback"
]

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = ["orders/create"]
  uri = "/webhooks/orders/create"

[app_proxy]
url = "https://example.com"
subpath = "apps/test-shop"
prefix = "apps"

[pos]
embedded = false
