api_version = "2025-10"

[[extensions]]
name = "w3w-checkout-ui"
handle = "w3w-checkout-ui"
type = "ui_extension"

[[extensions.targeting]]
module = "./src/index.tsx"
target = "purchase.checkout.delivery-address.render-after"

[extensions.capabilities]
api_access = true
network_access = true
